Add the service to add and edit the roles.
colmena-project/core-api pull request #18
Opened 2021-07-21 12:43 UTC by ferchuhill

This service possibility to add and edit the roles in the system. Is pending to check if the user can do this action

2021-07-21 13:07 UTC, santiagosemhan commented on src/cloud/services/RoleService.ts
> +    console.log(role);
remove console.log

2021-07-21 13:09 UTC, santiagosemhan requested changes

2021-07-21 13:09 UTC, santiagosemhan commented on src/cloud/routes/role.ts
> +    secure: false,
secure: true

2021-07-21 14:10 UTC, ferchuhill commented
add a secure route, remove the console.log and add the update the role into the role

2021-07-22 13:06 UTC, santiagosemhan approved these changes

2021-07-22 13:06 UTC, merged