Add the User change.
colmena-project/core-api pull request #19
Opened 2021-08-10 11:44 UTC by ferchuhill

add the schema and seed. Also, change the cloud function, add the functionality create, update and delete.

2021-08-10 12:20 UTC, santiagosemhan commented on src/cloud/classes/RecyclingCenter.ts
> +    await role.save(null,
check format here

2021-08-10 12:20 UTC, santiagosemhan commented on src/cloud/classes/RecyclingCenter.ts
> +    await UserService.clearUserSessions(user);
???

2021-08-10 12:23 UTC, santiagosemhan commented on src/cloud/controllers/UserController.ts
> +import { UserService } from '../services';
Review function names

2021-08-10 12:24 UTC, santiagosemhan commented on src/cloud/services/UserService.ts
> +const findUserAdmin = async (displayLimit: number, page: number): Promise<Parse.Object[]> => {
Review function names, and check if the user is admin based on the current user.

2021-08-10 21:40 UTC, ferchuhill reviewed
format the code, change the name of the services, and add the function to check if the user is admin

2021-08-17 12:14 UTC, santiagosemhan commented on src/cloud/services/UserService.ts
> +    if (factory !== undefined) {
replace with if (factory)

2021-08-18 16:33 UTC, ferchuhill reviewed
replace  syntax with undefined in the userService

2021-08-19 13:00 UTC, ferchuhill commented
replace syntax with undefined in the roleService

2021-08-19 14:55 UTC, santiagosemhan requested changes

2021-08-19 14:55 UTC, santiagosemhan commented on src/cloud/classes/index.ts
> +  Account, Address, Post, Container, Transaction, TransactionDetail,RecyclingCenter
Check space after the last comma.

2021-08-23 18:41 UTC, ferchuhill commented
change the schema the class user and role

2021-08-24 11:42 UTC, santiagosemhan approved these changes

2021-08-24 11:42 UTC, merged